files:
  - source: sites/**/contents
    ignore:
      - '*.jpg'
      - '*.png'
      - README.txt
      - '*.svg'
      - '*.gif'
      - '*.jpeg'
    translation: '%original_path%/%original_file_name%'
