# This Dockerfile can be used to pre-generate a container image
# with all required tools for content creators.
#
# Once published, it is used by the Dockerfile file
# and the WebStorm run configurations.

FROM node:14
ENV CHOKIDAR_USEPOLLING=1
ENV CHOKIDAR_INTERVAL=2500
ENV GATSBY_TELEMETRY_DISABLED=1
ENV INTERNAL_STATUS_PORT=33949
ENV GATSBY_CPU_COUNT=2
EXPOSE 8000
EXPOSE 33949

WORKDIR /jetbrains_guide/

# Copy all files (except those in .dockerignore)
COPY . .
RUN chmod +x /jetbrains_guide/guide.sh
RUN yarn

# Override the entry point defined in the node container otherwise headaches will happen
ENTRYPOINT []

CMD ["/jetbrains_guide/guide.sh"]