- label: resharper
  title: ReSharper
  subtitle: The Visual Studio Extension for .NET Developers.
  logo: './resharper.png'
  website: https://jetbrains.com/resharper
  body: |
    The Visual Studio Extension for .NET Developers!

    ## See Also
    - [ReSharper home page](https://www.jetbrains.com/resharper)
    - [ReSharper documentation](https://www.jetbrains.com/resharper/documentation/documentation.html)

- label: rider
  title: Rider
  subtitle: Fast & powerful, cross platform .NET IDE.
  logo: './rider.png'
  website: https://jetbrains.com/rider
  body: |
    Fast & powerful, cross platform .NET IDE. Develop .NET, ASP.NET, .NET Core, Xamarin or Unity applications on Windows, Mac, Linux.

    ## See Also
    - [Rider home page](https://www.jetbrains.com/rider)
    - [Rider documentation](https://www.jetbrains.com/rider/documentation/)